mindmap
  root((<b style="font-size: 20px">Bylovsjubileet</b>))
    id((Fra Landslov<br/>til Bylov))
      Omskriving av bolker
      Kongens plass
      Byordningen
      Europeiske paralleller
    id((Byloven og<br/>Skriftkultur))
      id)Bergens bylov<br/>i kontekst(
        Andre bylover i Norge
        Liknende lover i utlandet
        Retterbøter
        Diplomer og privilegier
      id)Andre tekster(
        Bjarkøyretten
        Farmannalov
        Hirdskrå
        Kongespeilet
      id)Skrift og språk(
        Skrivere og illuminatører
        Bylovens språk i diakroni
        Danske oversettelser
    id((Bergens Bylov))
      id)Bylov og byen(
        Brann og ombygging
        Offentlige bygg
        Handelsby Bergen
      id)Bylov og<br/>bergenserne(
        Myndigheter
        Hanseatene
        Den religiøse byen
      id)Årshjul(
        Året i byen
        Jula i byen
        Julevakt
      id[Video: Byloven og vekterne]
    id((Bylovens<br/>Etterliv))
      Bylovens utvikling
      Formannskapslov
      Filologi og historiografi